[package]
name = "convex_hull"
version = "0.1.0"
authors = ["Aceofsquares <btcr1990@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
